module.exports = {
  extends: [
    'stylelint-config-standard',
    // 'stylelint-config-standard-scss',
    'stylelint-config-recommended-scss',
    'stylelint-config-prettier',
    'stylelint-config-prettier-scss',
    'stylelint-config-property-sort-order-smacss',
  ],
  plugins: ['stylelint-order', 'stylelint-scss'],
  ignoreFiles: ['node_modules/**'],
  rules: {
    'at-rule-no-unknown': null,
    'property-no-unknown': [
      true,
      { ignoreProperties: ['composes'] }, // Emotion/MUI 스타일 특성
    ],
    'no-descending-specificity': null,
    'declaration-block-trailing-semicolon': null,
    'selector-class-pattern': null, // '^([a-z][a-z0-9]*)(-[a-z0-9]+)*$',
    'string-quotes': 'single',
    'scss/at-rule-conditional-no-parentheses': null,
    'declaration-empty-line-before': [
      'never',
      {
        ignore: ['after-declaration'], // 'first-nested', 'after-comment', 'after-declaration', 'inside-single-line-block',
      },
    ],
    // 'order/order': [
    //   'custom-properties',
    //   'dollar-variables',
    //   'declarations',
    //   'at-rules',
    //   'rules',
    //   { type: 'at-rule', name: 'media' },
    // ],

    // 'order/properties-order': [
    //   {
    //     groupName: 'Layout',
    //     noEmptyLineBetween: true,
    //     properties: [
    //       'display',
    //       'grid',
    //       'grid-column-gap',
    //       'grid-row-gap',
    //       'grid-auto-flow',
    //       'grid-auto-rows',
    //       'grid-auto-columns',
    //       'justify-items',
    //       'align-content',
    //       'place-items',
    //       'gap',
    //       'align-items',
    //       'justify-content',
    //       'flex-wrap',
    //       'flex-basis',
    //       'flex-grow',
    //       'flex-shrink',
    //       'flex',
    //       'align-self',
    //       'flex-direction',
    //       'visibility',
    //       'overflow',
    //       'overflow-block',
    //       'overflow-inline',
    //       'overflow-x',
    //       'overflow-y',
    //       '-webkit-overflow-scrolling',
    //       '-ms-overflow-x',
    //       '-ms-overflow-y',
    //       '-ms-overflow-style',
    //       'float',
    //       'clear',
    //       'position',
    //       'top',
    //       'right',
    //       'bottom',
    //       'left',
    //       'z-index',
    //     ],
    //   },
    //   {
    //     groupName: 'Box',
    //     emptyLineBefore: 'always',
    //     noEmptyLineBetween: true,
    //     properties: [
    //       'width',
    //       'min-width',
    //       'max-width',
    //       'height',
    //       'min-height',
    //       'max-height',
    //       'margin',
    //       'margin-top',
    //       'margin-right',
    //       'margin-bottom',
    //       'margin-left',
    //       'padding',
    //       'padding-top',
    //       'padding-right',
    //       'padding-bottom',
    //       'padding-left',
    //       'border',
    //       'border-top',
    //       'border-bottom',
    //       'border-right',
    //       'border-left',
    //       'border-style',
    //       'border-color',
    //       'border-top-width',
    //       'border-right-width',
    //       'border-bottom-width',
    //       'border-left-width',
    //       'border-top-style',
    //       'border-right-style',
    //       'border-bottom-style',
    //       'border-left-style',
    //       'border-top-color',
    //       'border-right-color',
    //       'border-bottom-color',
    //       'border-left-color',
    //       'border-top-left-radius',
    //       'border-top-right-radius',
    //       'border-bottom-right-radius',
    //       'border-bottom-left-radius',
    //       'outline',
    //       'outline-width',
    //       'outline-style',
    //       'outline-color',
    //       'outline-offset',
    //       'box-shadow',
    //       'clip',
    //       'vertical-align',
    //     ],
    //   },
    //   {
    //     groupName: 'Background',
    //     emptyLineBefore: 'always',
    //     noEmptyLineBetween: true,
    //     properties: [
    //       'background',
    //       'background-color',
    //       'background-image',
    //       'background-repeat',
    //       'background-attachment',
    //       'background-position',
    //       'background-clip',
    //       'background-origin',
    //       'background-size',
    //     ],
    //   },
    //   {
    //     groupName: 'Font',
    //     emptyLineBefore: 'always',
    //     noEmptyLineBetween: true,
    //     properties: [
    //       'font-family',
    //       'font-size',
    //       'font-style',
    //       'font-weight',
    //       'line-height',
    //       'color',
    //       'text-align',
    //       'text-decoration',
    //       'text-transform',
    //       'letter-spacing',
    //       'text-shadow',
    //       'white-space',
    //       'word-spacing',
    //       'word-break',
    //       'word-wrap',
    //       'text-indent',
    //       'direction',
    //       'unicode-bidi',
    //       'hyphens',
    //     ],
    //   },
    //   {
    //     groupName: 'Animation',
    //     emptyLineBefore: 'always',
    //     noEmptyLineBetween: true,
    //     properties: [
    //       'animation',
    //       'animation-name',
    //       'animation-duration',
    //       'animation-timing-function',
    //       'animation-delay',
    //       'animation-iteration-count',
    //       'animation-direction',
    //       'animation-fill-mode',
    //       'animation-play-state',
    //       'transition',
    //       'transition-property',
    //       'transition-duration',
    //       'transition-timing-function',
    //       'transition-delay',
    //     ],
    //   },
    //   {
    //     groupName: 'other',
    //     emptyLineBefore: 'always',
    //     noEmptyLineBetween: true,
    //     properties: [
    //       'content',
    //       'counter-reset',
    //       'counter-increment',
    //       'quotes',
    //       'list-style',
    //       'list-style-position',
    //       'list-style-type',
    //       'caption-side',
    //       'empty-cells',
    //       'table-layout',
    //       'pointer-events',
    //       'cursor',
    //       'resize',
    //       'overflow-wrap',
    //       'scroll-snap-type',
    //       'scroll-padding',
    //       'scroll-padding-top',
    //       'scroll-padding-right',
    //       'scroll-padding-bottom',
    //       'scroll-padding-left',
    //       'scroll-behavior',
    //       'scroll-snap-align',
    //       'scroll-snap-margin',
    //       'scroll-snap-stop',
    //       'scrollbar-width',
    //       'scrollbar-color',
    //     ],
    //   },
    // ],
  },
  overrides: [
    {
      files: ['src/**/*.{js,ts,jsx,tsx}'],
      customSyntax: 'postcss-styled-syntax',
    },
    {
      files: ['src/**/*.scss'],
      customSyntax: 'postcss-scss',
    },
    {
      files: ['src/**/*.css'],
      customSyntax: 'postcss',
    },
  ],
};
